### ISSUE TITLE
constructor and onconnected are called before component is composed

### ISSUE THREAD

**Issue by davidjamesstone** [WebReflection/ce-v0#1]
```html
<script src="https://unpkg.com/ce-v0@latest/min.js"></script>
<script src="https://unpkg.com/ce-v0@latest/comp.js"></script>
<script>
  const MyElement = new Component({
    name: 'my-element',
    static: {
      method () {
        console.log('Static method called')
      }
    },
    constructor () {
      MyElement.static()
      // => Uncaught TypeError: MyElement.static is not a function at HTMLElement.constructor
    },
    onconnected () {
      MyElement.static()
      // => Uncaught TypeError: MyElement.static is not a function at HTMLElement.onconnected
    }
  })
</script>
<my-element></my-element>
```

As you can see, calling a `static` function isn't possible in the constructor or onconnected due to `MyElement` not yet being defined.

Testing on MacOS v10.13.1/Chrome v63

**Comment by davidjamesstone** [comment]
Thanks for all your work in the CE/Web Components field BTW.
Your polyfills and posts are so important and helpful.

**Comment by WebReflection** [comment]
@davidjamesstone the static field is where you defined ... static fields ...
```js
static: {
      method () {
        console.log('Static method called')
      }
    },
```
this means that the class will have a public static method called **method**  ... try again:

```js
  const MyElement = new Component({
    name: 'my-element',
    static: {
      method () {
        console.log('Static method called')
      }
    },
    constructor () {
      MyElement.method()
    },
    onconnected () {
      MyElement.method()
    }
  })
```

**Comment by davidjamesstone** [comment]
Sorry Andrea, I messed up my example.
I get that the `static` object is for static methods and props. This issue is more about the sequencing of calls.
Let me try and spell it out better!

```html
<script src="https://unpkg.com/ce-v0@latest/min.js"></script>
<script src="https://unpkg.com/ce-v0@latest/comp.js"></script>

<x-tree></x-tree>
<script>
  console.log('Defining Tree')

  const Tree = new Component({
    name: 'x-tree',
    static: {
      method: () => {
      }
    },
    constructor () {
      console.log('constructor')
    },
    onconnected () {
      console.log('onconnected')
    },
    ondisconnected () {}
  })

  console.log('Tree defined')
</script>
```

Running the above logs:
1. Defining Tree
2. constructor
3. onconnected
4. Tree defined

Clearly, we can't use `static` methods in the constructor or onconnected because the Tree variable is not yet defined.

Moving the custom element declaration to the bottom (below the definition) changes the order of logging and "fixes" this.

```html
<script src="https://unpkg.com/ce-v0@latest/min.js"></script>
<script src="https://unpkg.com/ce-v0@latest/comp.js"></script>

<script>
  console.log('Defining Tree')

  const Tree = new Component({
    name: 'x-tree',
    static: {
      method: () => {
      }
    },
    constructor () {
      console.log('constructor')
    },
    onconnected () {
      console.log('onconnected')
    },
    ondisconnected () {}
  })

  console.log('Tree defined')
</script>
<x-tree></x-tree>
```

Running the above logs:
1. Defining Tree
2. Tree defined
3. constructor
4. onconnected


I'm not sure if this is what you would expect but this behaviour baffled me for a while.

(The issue is compounded when using browserify bundler but I'm looking into that separately)

**Comment by WebReflection** [comment]
that's how V0 is, the component is just a convenient way to define classes but you need classes to be already known if you want to access their static methods.

V0 works defining only a prototype, the constructor is returned once defined so if its methods get called before it's returned it will inevitably fail.

Maybe a caveat to specify in the README? or you'd rather force async invokes? 'cause that usually means *flicking* DOM which is never desired.

V1 has classes definition before, so you `customElements.define(name, Class)` when `Class` is already defined but `document.registerElement` is the one that returns the class.

Is it clear to you what's going on, now?

**Comment by WebReflection** [comment]
FWIW I've added a caveat section under Component in the README. Thanks for pointing this gotcha out.

**Comment by davidjamesstone** [comment]
Yes that's clear, thanks for the explanation Andrea.

I prefer the v1 api but I'm swayed by your arguments to use v0 for now and your `Component` wrapper will make migration to v1 easier when the time comes.

Thanks again for all your help and work.
