### ISSUE TITLE
Is this logic part of document-register-element v1 polyfill?

### ISSUE THREAD

**Issue by dogoku** [WebReflection/ce-v0#2]
Hey @WebReflection thanks for all your hard work ❤️

Please correct me if I am wrong, but I was wondering why does your [document-register-element](https://github.com/WebReflection/document-register-element) not have the same logic of "use v1 spec if available" ? 

Basically I was expecting that calling `require('document-register-element')` would do
- something similar to `ce-v0` for browsers that already implement v1 spec
- execute the full polyfill code for browsers that don't implement the v1 spec

Would this behaviour eventually land in the main polyfill (if not by default, maybe something opt-in, like  `document-register-element/grampafill`) or is there some fundamental difference between the specs that is preventing us from doing so?

I think that the idea suggested in this package is truly brilliant and it's a shame to see it grow stale :)

Thanks for your time

**Comment by WebReflection** [comment]
This is DRE code without CE built-ins extends, is meant to cover a specific use case.

**Comment by dogoku** [comment]
What about the use case of people wanting to use v0 and v1 spec at the same time, but take advantage of native implementations where possible?

To give a bit more background, given a codebase that has both v0 and v1 CEs, modern browsers that implement the v1 spec natively could opt for the `grandpafill`, as you put in your article, instead of the full-fat polyfill. For Example

```js
// index-legacy.js - IE11 & Edge
require('document-register-element');
//...
require('thirdparty-v0-element');
require('my-v1-element');
```

```js
// index-modern.js - Chrome, FF, Safari, etc
import "document-register-element/grandpafill";
//...
import 'thirdparty-v0-element';
import 'my-v1-element';
```

Would you consider a PR in [DRE](https://github.com/WebReflection/document-register-element) that provides something like this?

**Comment by WebReflection** [comment]
> Would you consider a PR in DRE that provides something like this?

No. DRE is on the deprecation path, and it's used in projects too big to change.

On top of that, you can already do what you describe, you just include DRE on top of your page only if `window.customElements` is not present, and you do whatever else you need to do after.

It's explained in the DRE readme, here:
https://github.com/WebReflection/document-register-element#important-how-to-migrate-to-native-v1

Last, but not least, V0 is dead. Time to move forward.

**Comment by dogoku** [comment]
Thanks for the response. I won't take anymore of your time.
